// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePeople = "users"

// People mapped from table <users>
type People struct {
	UUID    string `gorm:"column:uuid" json:"uuid"`
	Name    string `gorm:"column:name" json:"name"`
	Age     int64  `gorm:"column:age" json:"age"`
	Version int64  `gorm:"column:version" json:"version"`
}

// TableName People's table name
func (*People) TableName() string {
	return TableNamePeople
}
